# App config schema

translations.en."app-name" = { category = "translations", type = "string", name = "应用程序名称", description = "整个应用程序使用的名称。" }
translations.en."app-description" = { category = "translations", type = "string", name = "应用程序描述", description = "应用描述在整个应用中使用。" }
translations.en."app-tagline" = { category = "translations", type = "string", name = "应用标语", description = "更短的应用描述在整个应用中使用。" }
translations.en."company-name" = { category = "translations", type = "string", name = "公司名称", description = "整个应用程序使用的公司名称。" }
translations.en."share-hashtag" = { category = "translations", type = "string", name = "分享标签", description = "在分享消息时使用的标签。" }
translations.en."contact-email" = { category = "translations", type = "string", name = "联系电子邮件", description = "一般联系邮箱。" }
translations.en."settings.community" = { category = "translations", type = "string", name = "社区提示", description = "提示加入您的社区。" }

translations.en."app-full-name" = { category = "translations", type = "string", internal = "true" }
translations.en."app-twitter-user" = { category = "translations", type = "string", internal = "true" }
translations.en."editor-name" = { category = "translations", type = "string", internal = "true" }

features.disable_sign_up = { category = "features", type = "boolean", name = "禁止创建帐户", description = "阻止访问者创建帐户。帐户必须由管理员创建。" }
features.show_terms = { category = "features", type = "boolean", name = "显示使用条款", description = "显示使用条款的链接。" }
features.show_privacy = { category = "features", type = "boolean", name = "显示隐私通知", description = "显示隐私通知的链接。" }
features.show_controls_link = { category = "features", type = "boolean", name = "显示控件", description = "显示指向控件文档的链接。" }
features.show_docs_link = { category = "features", type = "boolean", name = "显示文档链接", description = "显示到文档的链接。" }
features.show_features_link = { category = "features", type = "boolean", name = "显示功能链接", description = "显示功能文档的链接。" }
features.show_community_link = { category = "features", type = "boolean", name = "显示社区链接", description = "显示与你的社区的链接。" }
features.show_company_logo = { category = "features", type = "boolean", name = "展示公司标志", description = "在整个应用程序中显示公司的logo。" }
features.show_issue_report_link = { category = "features", type = "boolean", name = "显示问题报告链接", description = "显示用于报告问题的链接。" }
features.show_avatar_editor_link = { category = "features", type = "boolean", name = "显示头像编辑器链接", description = "显示头像编辑器的链接，如Quilt。", internal = "true" }
features.show_avatar_pipelines_link = { category = "features", type = "boolean", name = "显示头像管道", description = "显示指向avatar管道信息的链接。" }
features.show_model_collection_link = { category = "features", type = "boolean", name = "显示模型集合Link", description = "显示到模型集合的链接。" }
features.hide_powered_by = { category = "features", type = "boolean", name = "皮革由集线器供电", description = "隐藏首页和加载页面上的“Powered by Hubs Cloud”通知。" }
features.public_rooms = { category = "features", type = "boolean", name = "公共房间", description = "允许访客将房间设置为公共空间，以在主页上展示它们。" }
features.default_room_id = { category = "features", type = "string", name = "主页室号", description = "使用指定的房间来代替主页。"}
features.enable_spoke = { category = "features", type = "boolean", name = "启用场景编辑器", description = "为所有访问者启用场景编辑器。"}
features.enable_lobby_ghosts = { category = "features", type = "boolean", name = "启用大堂幽灵", description = "让大堂的人探索房间，同时保持隐形和听不见。" }
features.public_api_access = { category = "features", type = "boolean", name = "访问公共API", description = "启用可公开访问的API，以编程方式管理后端资源。", internal = "false" }

features.permissive_rooms = { category = "rooms", type = "boolean", name = "宽容的房间", description = "启用新房间的完全内容创建权限。" }
features.disable_room_creation = { category = "rooms", type = "boolean", name = "禁止创建房间", description = "禁止为非管理员创建房间。" }
features.require_account_for_join = { category = "rooms", type = "boolean", name = "需要进入房间的帐号", description = "需要访问房间的帐号。" }
features.default_room_size = { category = "rooms", type = "number", name = "默认房间大小", description = "新房间的默认房间大小。这并不包括大厅的用户。" }
features.max_room_size = { category = "rooms", type = "number", name = "最大房间面积", description = "访客可设定的最大房间尺寸。" }

features.show_feature_panels = { category = "features", type = "boolean", internal = "true" }
features.show_join_us_dialog = { category = "features", type = "boolean", internal = "true" }
features.show_discord_bot_link = { category = "features", type = "boolean", internal = "true" }
features.show_whats_new_link = { category = "features", type = "boolean", internal = "true" }
features.show_source_link = { category = "features", type = "boolean", internal = "true" }
features.show_feedback_ui = { category = "features", type = "boolean", internal = "true" }
features.show_issue_report_dialog = { category = "features", type = "boolean", internal = "true" }
features.show_cloud = { category = "features", type = "boolean", internal = "true" }
features.show_newsletter_signup = { category = "features", type = "boolean", internal = "true" }
features.change_hub_near_room_links = { category = "features", type = "boolean", internal = "true" }
features.is_locked_down_demo_room = { category = "features", type = "string", internal = "true", description = "A comma separated list of hubIds to be designated as demo rooms with simplified UI." }

images.logo = { category = "images", type = "file", name = "Hub Logo", description = "Appears throughout your hub including lobby and loading screens." }
images.logo_dark = { category = "images", type = "file", name = "Hub logo for dark mode", description = "The hub logo which appears for visitors who have dark mode enabled." }
images.favicon = { category = "images", type = "file", name = "Favicon", description = "The favicon is the small picture which appears in the web browser tab." }
images.home_background = { category = "images", type = "file", name = "Homepage image", description = "The main image used to decorate your hub's home page." }
images.company_logo = { category = "images", type = "file", name = "Company Logo", description = "An optional logo which appears in the footer of your hub's home page." }
images.app_icon = { category = "images", type = "file", name = "Shortcut icon", description = "Used when a shortcut to your hub is added to a user's device." }
images.app_thumbnail = { category = "images", type = "file", name = "Social media card", description = "Used when links to your hub are shared on social media." }
images.editor_logo = { category = "images", type = "file", internal = "true" }
images.landing_rooms_thumb = { category = "images", type = "file", internal = "true" }
images.landing_communicate_thumb = { category = "images", type = "file", internal = "true" }
images.landing_media_thumb = { category = "images", type = "file", internal = "true" }

theme.dark-theme = { category = "theme", type = "boolean", name = "Dark Mode", description = "[deprecated] Use dark UI styling.", deprecated="true" }
theme.action-color = { category = "theme", type = "color", name = "Primary Color", description = "[deprecated] Call to action button color.", deprecated="true" }
theme.action-color-highlight = { category = "theme", type = "color", name = "Highlighted Primary Color", description = "[deprecated] Highlighted call to action color.", deprecated="true" }
theme.action-color-disabled = { category = "theme", type = "color", name = "Disabled Primary Color", description = "[deprecated] Disabled call to action color.", deprecated="true" }
theme.action-text-color = { category = "theme", type = "color", name = "Primary Text Color", description = "[deprecated] Call to action button text color.", deprecated="true" }
theme.action-subtitle-color = { category = "theme", type = "color", name = "Primary Subtitle Color", description = "[deprecated] Call to action button subtitle text color.", deprecated="true" }
theme.action-label-color = { category = "theme", type = "color", name = "Primary Label Color", description = "[deprecated] Call to action label color.", deprecated="true" }
theme.notice-background-color = { category = "theme", type = "color", name = "Secondary Color", description = "[deprecated] Notice and indicator color.", deprecated="true" }
theme.notice-text-color = { category = "theme", type = "color", name = "Secondary Text Color", description = "[deprecated] Notice and indicator text color.", deprecated="true" }
theme.notice-widget-color = { category = "theme", type = "color", name = "Secondary Widget Color", description = "[deprecated] Notice and indicator UI widget color.", deprecated="true" }
theme.favorited-color = { category = "theme", type = "color", name = "Favorited Color", description = "[deprecated] Favorited Color", deprecated = "true" }
theme.nametag-color = { category = "theme", type = "color", name = "Background Color", description="The background color of nametags which float above each room guest." }
theme.nametag-text-color = { category = "theme", type = "color", name = "Text Color", description="The text color of nametags which float above each room guest." }
theme.themes = { category = "theme", type = "json", name = "Themes", description = "A json array describing custom client themes."}

links.terms_of_use = { category = "links", type = "string", name = "使用条款", description = "使用条款链接到您的使用条款页面。"}
links.privacy_notice = { category = "links", type = "string", name = "隐私声明", description = "链接到您的隐私页面。"}
links.controls = { category = "links", type = "string", name = "控制文档", description = "链接到控件文档。"}
links.features = { category = "links", type = "string", name = "功能文档", description = "链接到功能文档。"}
links.community = { category = "links", type = "string", name = "社区", description = "链接到你的社区。"}
links.docs = { category = "links", type = "string", name = "文献", description = "链接到您的文档。"}
links.issue_report = { category = "links", type = "string", name = "问题报告", description = "报告问题的链接。"}
links.promotion = { category = "links", type = "string", name = "促销信息", description = "链接到关于促销信息和许可的信息。"}
links.remixing = { category = "links", type = "string", name = "重新合成信息", description = "链接到关于混音信息和许可的信息。"}
links.model_collection = { category = "links", type = "string", name = "模型收藏", description = "链接到推荐模型的集合。"}

auth.login_subject = { category = "auth", type="string", name="神奇链接邮件主题", description="自定义登录用户的邮件主题" }
auth.login_body = { category = "auth", type="longstring", name="神奇链接邮件正文", description="自定义消息。添加` {{link}} `来插入魔法链接，否则它将被添加到末尾。" }