# App config schema

translations.en."app-name" = { category = "translations", type = "string", name = "App Name", description = "整个应用程序使用的名称。" }
translations.en."app-description" = { category = "translations", type = "string", name = "App Description", description = "应用描述在整个应用中使用。" }
translations.en."app-tagline" = { category = "translations", type = "string", name = "App Tagline", description = "更短的应用描述在整个应用中使用。" }
translations.en."company-name" = { category = "translations", type = "string", name = "Company Name", description = "整个应用程序使用的公司名称。" }
translations.en."share-hashtag" = { category = "translations", type = "string", name = "Share Hashtag", description = "在分享消息时使用的标签。" }
translations.en."contact-email" = { category = "translations", type = "string", name = "Contact email", description = "一般联系邮箱。" }
translations.en."settings.community" = { category = "translations", type = "string", name = "Community Prompt", description = "提示加入您的社区。" }

translations.en."app-full-name" = { category = "translations", type = "string", internal = "true" }
translations.en."app-twitter-user" = { category = "translations", type = "string", internal = "true" }
translations.en."editor-name" = { category = "translations", type = "string", internal = "true" }

features.disable_sign_up = { category = "features", type = "boolean", name = "Disable account creation", description = "阻止访问者创建帐户。帐户必须由管理员创建。" }
features.show_terms = { category = "features", type = "boolean", name = "Show Terms of Use", description = "显示使用条款的链接。" }
features.show_privacy = { category = "features", type = "boolean", name = "Show Privacy Notice", description = "显示隐私通知的链接。" }
features.show_controls_link = { category = "features", type = "boolean", name = "Show Controls Links", description = "显示指向控件文档的链接。" }
features.show_docs_link = { category = "features", type = "boolean", name = "Show Docs Links", description = "显示到文档的链接。" }
features.show_features_link = { category = "features", type = "boolean", name = "Show Features Links", description = "显示功能文档的链接。" }
features.show_community_link = { category = "features", type = "boolean", name = "Show Community Links", description = "显示与你的社区的链接。" }
features.show_company_logo = { category = "features", type = "boolean", name = "Show Company Logo", description = "在整个应用程序中显示公司的logo。" }
features.show_issue_report_link = { category = "features", type = "boolean", name = "Show Issue Report Link", description = "显示用于报告问题的链接。" }
features.show_avatar_editor_link = { category = "features", type = "boolean", name = "Show Avatar Editor Links", description = "显示头像编辑器的链接，如Quilt。", internal = "true" }
features.show_avatar_pipelines_link = { category = "features", type = "boolean", name = "Show Avatar Pipelines Links", description = "显示指向avatar管道信息的链接。" }
features.show_model_collection_link = { category = "features", type = "boolean", name = "Show Model Collection Link", description = "显示到模型集合的链接。" }
features.hide_powered_by = { category = "features", type = "boolean", name = "Hide Powered By Hubs", description = "隐藏首页和加载页面上的“Powered by Hubs Cloud”通知。" }
features.public_rooms = { category = "features", type = "boolean", name = "Public Rooms", description = "允许访客将房间设置为公共空间，以在主页上展示它们。" }
features.default_room_id = { category = "features", type = "string", name = "Homepage Room ID", description = "使用指定的房间来代替主页。"}
features.enable_spoke = { category = "features", type = "boolean", name = "Enable Scene Editor", description = "为所有访问者启用场景编辑器。"}
features.enable_lobby_ghosts = { category = "features", type = "boolean", name = "Enable Lobby Ghosts", description = "让大堂的人探索房间，同时保持隐形和听不见。" }
features.public_api_access = { category = "features", type = "boolean", name = "Public API Access", description = "启用可公开访问的API，以编程方式管理后端资源。", internal = "false" }

features.permissive_rooms = { category = "rooms", type = "boolean", name = "Permissive Rooms", description = "启用新房间的完全内容创建权限。" }
features.disable_room_creation = { category = "rooms", type = "boolean", name = "Disable room creation", description = "禁止为非管理员创建房间。" }
features.require_account_for_join = { category = "rooms", type = "boolean", name = "Require accounts for room access", description = "需要访问房间的帐号。" }
features.default_room_size = { category = "rooms", type = "number", name = "Default room size", description = "新房间的默认房间大小。这并不包括大厅的用户。" }
features.max_room_size = { category = "rooms", type = "number", name = "Maximum room size", description = "访客可设定的最大房间尺寸。" }

features.show_feature_panels = { category = "features", type = "boolean", internal = "true" }
features.show_join_us_dialog = { category = "features", type = "boolean", internal = "true" }
features.show_discord_bot_link = { category = "features", type = "boolean", internal = "true" }
features.show_whats_new_link = { category = "features", type = "boolean", internal = "true" }
features.show_source_link = { category = "features", type = "boolean", internal = "true" }
features.show_feedback_ui = { category = "features", type = "boolean", internal = "true" }
features.show_issue_report_dialog = { category = "features", type = "boolean", internal = "true" }
features.show_cloud = { category = "features", type = "boolean", internal = "true" }
features.show_newsletter_signup = { category = "features", type = "boolean", internal = "true" }
features.change_hub_near_room_links = { category = "features", type = "boolean", internal = "true" }
features.is_locked_down_demo_room = { category = "features", type = "string", internal = "true", description = "用逗号分隔的hubIds列表将被指定为具有简化UI的演示房间。" }

images.logo = { category = "images", type = "file", name = "Hub Logo", description = "Appears throughout your hub including lobby and loading screens." }
images.logo_dark = { category = "images", type = "file", name = "Hub logo for dark mode", description = "The hub logo which appears for visitors who have dark mode enabled." }
images.favicon = { category = "images", type = "file", name = "Favicon", description = "The favicon is the small picture which appears in the web browser tab." }

images.home_background = { category = "images", type = "file", name = "Homepage image", description = "The main image used to decorate your hub's home page." }
images.company_logo = { category = "images", type = "file", name = "Company Logo", description = "An optional logo which appears in the footer of your hub's home page." }

images.app_icon = { category = "images", type = "file", name = "Shortcut icon", description = "Used when a shortcut to your hub is added to a user's device." }
images.app_thumbnail = { category = "images", type = "file", name = "Social media card", description = "Used when links to your hub are shared on social media." }



images.editor_logo = { category = "images", type = "file", internal = "true" }
images.landing_rooms_thumb = { category = "images", type = "file", internal = "true" }
images.landing_communicate_thumb = { category = "images", type = "file", internal = "true" }
images.landing_media_thumb = { category = "images", type = "file", internal = "true" }

theme.dark-theme = { category = "theme", type = "boolean", name = "Dark Mode", description = "[已弃用]使用深色UI样式", deprecated="true" }
theme.action-color = { category = "theme", type = "color", name = "Primary Color", description = "[已弃用]呼叫操作按钮颜色", deprecated="true" }
theme.action-color-highlight = { category = "theme", type = "color", name = "Highlighted Primary Color", description = "[已弃用]高亮号召行动颜色。", deprecated="true" }
theme.action-color-disabled = { category = "theme", type = "color", name = "Disabled Primary Color", description = "[已弃用]禁用call to action颜色。", deprecated="true" }
theme.action-text-color = { category = "theme", type = "color", name = "Primary Text Color", description = "[已弃用]呼叫动作按钮文字颜色。", deprecated="true" }
theme.action-subtitle-color = { category = "theme", type = "color", name = "Primary Subtitle Color", description = "[已弃用]呼叫动作按钮字幕文字颜色", deprecated="true" }
theme.action-label-color = { category = "theme", type = "color", name = "Primary Label Color", description = "[已弃用]号召行动标签颜色。", deprecated="true" }
theme.notice-background-color = { category = "theme", type = "color", name = "Secondary Color", description = "[已弃用]通知和指示器颜色。", deprecated="true" }
theme.notice-text-color = { category = "theme", type = "color", name = "Secondary Text Color", description = "[已弃用]通知和指示符文本颜色。", deprecated="true" }
theme.notice-widget-color = { category = "theme", type = "color", name = "Secondary Widget Color", description = "[已弃用]通知和指示UI widget颜色", deprecated="true" }
theme.favorited-color = { category = "theme", type = "color", name = "Favorited Color", description = "[弃用]最喜欢的颜色", deprecated = "true" }
theme.nametag-color = { category = "theme", type = "color", name = "Background Color", description="每个房间客人上方的名牌的背景色。" }
theme.nametag-text-color = { category = "theme", type = "color", name = "Text Color", description="名字牌的文字颜色浮动在每个房间的客人。" }
theme.themes = { category = "theme", type = "json", name = "Themes", description = "描述自定义客户端主题的json数组。"}

links.terms_of_use = { category = "links", type = "string", name = "Terms of Use", description = "链接到您的使用条款页面。"}
links.privacy_notice = { category = "links", type = "string", name = "Privacy Notice", description = "链接到您的隐私页面。"}
links.controls = { category = "links", type = "string", name = "Controls Documentation", description = "链接到控件文档。"}
links.features = { category = "links", type = "string", name = "Features Documentation", description = "链接到功能文档。"}
links.community = { category = "links", type = "string", name = "Community", description = "链接到你的社区。"}
links.docs = { category = "links", type = "string", name = "Docs", description = "链接到您的文档。"}
links.issue_report = { category = "links", type = "string", name = "Issue Report", description = "报告问题的链接。"}
links.promotion = { category = "links", type = "string", name = "Promotion Info", description = "链接到关于促销信息和许可的信息。"}
links.remixing = { category = "links", type = "string", name = "Remixing Info", description = "链接到关于混音信息和许可的信息。"}
links.model_collection = { category = "links", type = "string", name = "Model Collection", description = "链接到推荐模型的集合。"}

auth.login_subject = { category = "auth", type="string", name="Magic Link Email Subject", description="自定义登录用户的邮件主题

" }
auth.login_body = { category = "auth", type="longstring", name="Magic Link Email Body", description="自定义消息。添加` {{link}} `来插入魔法链接，否则它将被添加到末尾。" }
